### ISSUE TITLE
IndexError: pop index out of range

### ISSUE THREAD

**Issue by igorsf** [derek73/python-nameparser#54]
Unable to parse the following name

>>> from nameparser import HumanName
>>> name = HumanName("Claus SchroederVP of");

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/igorsf/venv/downloader/local/lib/python2.7/site-packages/nameparser/parser.py", line 82, in __init__
    self.full_name = full_name
  File "/home/igorsf/venv/downloader/local/lib/python2.7/site-packages/nameparser/parser.py", line 348, in full_name
    self.parse_full_name()
  File "/home/igorsf/venv/downloader/local/lib/python2.7/site-packages/nameparser/parser.py", line 430, in parse_full_name
    pieces = self.parse_pieces(parts)
  File "/home/igorsf/venv/downloader/local/lib/python2.7/site-packages/nameparser/parser.py", line 579, in parse_pieces
    return self.join_on_conjunctions(output, additional_parts_count)
  File "/home/igorsf/venv/downloader/local/lib/python2.7/site-packages/nameparser/parser.py", line 672, in join_on_conjunctions
    pieces.pop(i)
IndexError: pop index out of range

```

**Comment by derek73** [comment]
Just pushed v0.5.1 to pypi. Should fix this.
